version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0

executors:
  rsp:
    docker:
      - image: cimg/node:12.22
    environment:
      CACHE_VERSION: v1
    working_directory: ~/react-spectrum

  rsp-large:
    docker:
      - image: cimg/node:12.22
    resource_class: large
    environment:
      CACHE_VERSION: v1
    working_directory: ~/react-spectrum

  rsp-xlarge:
    docker:
      - image: cimg/node:12.22
    resource_class: xlarge
    environment:
      CACHE_VERSION: v1
    working_directory: ~/react-spectrum

jobs:
  install:
    executor: rsp-large
    steps:
      - checkout
      - restore_cache:
          keys:
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Write npmrc
          command: |
            if [ $NPM_PASSWORD ]; then
              cp .circleci/.npmrc .npmrc
            fi

      - run:
          name: build
          command: |
            yarn --pure-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
         paths:
           - ~/.cache/yarn
         key: rsp-yarn-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - ~/react-spectrum
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

  install-17:
    executor: rsp-large
    steps:
      - checkout
      - restore_cache:
          keys:
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - rsp-yarn-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: build
          command: |
            yarn install --pure-lockfile --cache-folder ~/.cache/yarn && yarn install-17 --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/react-spectrum
          key: react-spectrum17-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

  test-ssr:
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test ssr
          command: yarn test:ssr

  test:
    parallelism: 3
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run: mkdir ~/junit

      - run:
          name: test
          command: |
            shopt -s globstar
            TESTFILES=$(circleci tests glob "packages/**/*.test.[tj]{s,sx}" | circleci tests split --split-by=timings)
            yarn test ${TESTFILES}

      - run:
          command: |
            cat junit.xml
            cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  test-ssr-17:
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum17-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: test ssr
          command: |
            yarn test:ssr

  test-17:
    parallelism: 3
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum17-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run: mkdir ~/junit

      - run:
          name: test
          command: |
            shopt -s globstar
            TESTFILES=$(circleci tests glob "packages/**/*.test.[tj]{s,sx}" | circleci tests split --split-by=timings)
            JEST_JUNIT_OUTPUT_NAME="junit-17.xml" yarn test ${TESTFILES}

      - run:
          command: cp junit-17.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  lint:
    executor: rsp
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: lint
          command: yarn lint

  storybook:
    executor: rsp-large
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook
          command: make storybook

      - persist_to_workspace:
          root: dist
          paths:
            - '*/storybook/'

  storybook-17:
    executor: rsp-large
    steps:
      - restore_cache:
          key: react-spectrum17-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build storybook-17
          command: make storybook-17

      - persist_to_workspace:
          root: dist
          paths:
            - '*/storybook-17/'

  docs:
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website

      - persist_to_workspace:
          root: dist
          paths:
            - '*/docs/'

  docs-production:
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: build docs
          command: make website-production

      - persist_to_workspace:
          root: dist
          paths:
            - '*/docs/'

  verdaccio-test:
    executor: rsp-xlarge
    steps:
      # Figure out what exactly this cache contains.
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      # Will need to test if the script can run properly
      - run:
          name: run verdaccio
          command: ./scripts/verdaccio.sh

      # Figure out if this works, aim is to persist the dist created by the script
      # I think this may conflict with the current deploy-production, may need to modify the script so it stores
      # it somewhere else? Perhaps have the script run before the prod one and have it rename the dist/production/docs folder to dist/verdaccio/docs
      # That way we have a unique link that doesn't conflict with the prod link?
      - persist_to_workspace:
          root: dist
          paths:
            - '*/docs/'

  deploy:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: |
            if [ $AZURE_STORAGE_SAS_TOKEN ]; then
              az storage blob upload-batch -d reactspectrum -s /tmp/dist --account-name reactspectrum
            fi

  # Double check the command below. The reason this is split out instead of using deploy-production is so we don't increase the chance
  # of failure (deploy-production doesnt run a lot of the time cuz docs-production fails). Figure out if I can
  # get rid of this and place verdaccio-test under deploy (prob don't wanna do that cuz verdaccio-test is basically doing docs-production and may fail a bunch)
  deploy-verdaccio:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: ls /tmp/dist/verdaccio
          # command: |
          #   if [ $AZURE_STORAGE_SAS_TOKEN ]; then
          #     az storage blob upload-batch -d reactspectrum -s /tmp/dist/verdaccio --account-name reactspectrum
          #   fi

  deploy-production:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: /tmp/dist
      - run:
          name: deploy
          command: az storage blob upload-batch -d "\$web" -s /tmp/dist/production/docs --account-name reactspectrum

  comment:
    executor: rsp
    steps:
      - checkout
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: comment on pr
          command: |
            if [ $GITHUB_TOKEN ]; then
              node .circleci/comment.js
            fi

  publish-nightly:
    executor: rsp-xlarge
    steps:
      - restore_cache:
          key: react-spectrum-{{ .Environment.CACHE_VERSION }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Authenticate with npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            git update-index --skip-worktree .npmrc
      - run:
          name: Publish
          command: make publish-nightly

workflows:
  version: 2
  commit:
    jobs:
      - install
      - install-17
      - test-ssr:
          requires:
            - install
      - test:
          requires:
            - install
      - test-ssr-17:
          requires:
            - install-17
      - test-17:
          requires:
            - install-17
      - lint:
          requires:
            - install
      - storybook:
          requires:
            - install
      - storybook-17:
          requires:
            - install-17
      - docs:
          requires:
            - install
      - docs-production:
          filters:
            branches:
              only: main
          requires:
            - install
      - verdaccio-test:
      # Approach: Only run on commits to main? This means we won't have a comment on a PR though.
          # filters:
          #   branches:
          #     only: main
          requires:
            - install
      - deploy:
          requires:
            - lint
            - test-ssr
            - test
            - test-ssr-17
            - test-17
            - storybook
            - storybook-17
            - docs
      - deploy-production:
          filters:
            branches:
              only: main
          requires:
            - docs-production
      - deploy-verdaccio:
          # filters:
          #   branches:
          #     only: main
          requires:
            - verdaccio-test
      - comment:
          requires:
            - deploy

  nightly:
    triggers:
      - schedule:
          cron: "0 9 * * *" # 02:00 PDT
          filters:
            branches:
              only:
                - main
    jobs:
      - install
      - publish-nightly
